app/assets/javascripts/application.js, app/models/user.rb, app/views/devise/registrations/edit.html.erb, db/migrate/20160410184759_add_columns_to_user.rb, db/schema.rb
Apenas add os campos no banco e editei o formulário de edição de usuário.
=> Add filds in user register

app/views/devise/passwords/edit.html.erb
=> Fix translate on password edit

app/controllers/registrations_controller.rb
This is just about making code cleaner (more organized) and less redundant (there were two `protected` statements in there). Plus, this is my first PR made for this project, so I'm just warming up. ;)
=> Improve RegistrationsController code organizartion and remove redundancy

Gemfile, Gemfile.lock, app/controllers/omniauth_callbacks_controller.rb, app/models/user.rb, app/views/devise/sessions/new.html.erb, config/initializers/devise.rb, db/migrate/20161030015207_add_change_column_null_to_user_email.rb
Este PR implementa o sign in pelo Twitter
=> Implement signin by twitter

config/initializers/devise.rb
Add config para habilitar o download do avatar do facebook
=> Add :secure_image_url => true in config facebook

app/models/user.rb
Altera or e and para || e &&, e corrigi identação
=> [app/models] Edita model user

app/views/layouts/_footer.html.erb
=> inserindo link para github 

.rubocop.yml
* Adiciona arquivo de configuração do rubocop
=> Add rubocop config file

Gemfile, Gemfile.lock, spec/controllers/event_registrations_controller_spec.rb, spec/controllers/events_controller_spec.rb, spec/controllers/paginas_controller_spec.rb
* Adiciona chave params para testes de controllers
Issue relacionada #149
=> Corrige erros nos testes do rspec #149

.gitignore, Vagrantfile, bootstrap.sh
=> Fixed Vagrant Configs

Gemfile, Gemfile.lock, app/finders/financial_transaction_finder.rb
some updates in go_blog finders, and financial transactions finders
go_blog is update for new version
=> update gemfile and finders

app/views/events/show.html.erb
Solves #245: 
Changes the show file in events to show start and end date.
The format used was "%e %b %Y, %H:%M".
=> Show start and end date in event

Gemfile.lock
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.
Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are available
here
Thanks for contributing to GoRails!
=> udpate gemfile lock

Gemfile.lock
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.
Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are available
here
Thanks for contributing to GoRails!
=> deploy error because sqllite in engine

app/controllers/users_controller.rb, app/views/users/certified.html.erb, app/views/users/show_certified.html.erb, config/locales/pt-BR/views/certified.yml, config/routes.rb
Adicionado action no controller users para validar a existência do código do certificado, assim como a rota e as views.
=> Tela de validar certificado issue #256

config/initializers/rollbar.rb
add conf for rollbar integration
=> add rollbar confg

app/models/registration.rb
Alteração no método code_certified e adicionado validates_uniqueness_of da coluna certified_code.
=> Adicionada validação de sempre criar código de certificado único. fixed #283

Gemfile, Gemfile.lock
update engine go_blog, resolving issue 246
=> update go_blog engine

README.md, db/schema.rb
=> tarefa #302

.gitignore
add vendor folder to .gitignore
=> add vendor folder to .gitignore

app/views/errors/error404.erb, app/views/errors/error422.erb, app/views/errors/error500.erb, app/views/layouts/_footer.html.erb
=> tarefa #315

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.css, app/views/events/show.html.erb, config/locales/pt-BR/pt-BR.yml
Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.
If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.
Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are available
here
Thanks for contributing to GoRails!
=> tarefa #318

app/decorators/event_decorator.rb, app/models/event.rb, app/views/events/_collection_admin.html.erb, config/locales/pt-BR/models/event.yml, config/locales/pt-BR/views/events.yml
=> tarefa #320

app/helpers/users_helper.rb, app/models/social_network.rb, app/models/social_network_type.rb, app/views/devise/registrations/edit.html.erb, app/views/users/show.html.erb, db/migrate/20171031232736_create_social_network_types.rb, db/migrate/20171031233731_add_social_network_type_to_social_network.rb, lib/tasks/dev.rake, spec/models/social_network_type_spec.rb
Criada uma tabela que guarda os tipos das redes sociais. Mostrar esse tipos na tela de editar perfil do usuário. Assim como mostrar as redes sociais cadastradas no show do usuário.
=> Selecionar a Rede Social no perfil do usuário issue #183

spec/controllers/events_controller_spec.rb, spec/models/event_spec.rb
=> pass rspec tests

app/controllers/home_controller.rb, app/models/event.rb, app/views/home/_sidebar.html.erb, app/views/home/_sidebar_events.html.erb, app/views/home/_sidebar_jobs.html.erb, app/views/home/_sidebar_social.html.erb, app/views/home/_sidebar_transactions.html.erb, app/views/home/index.html.erb, app/views/users/_tab_user_data.html.erb, app/views/users/show.html.erb, db/schema.rb
coloquei no index uma barra lateral com 5 ultimas vagas de emprego e proximos 5 eventos
=> tarefa #351

app/controllers/users_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/events/show.html.erb, config/locales/pt-BR/views/events.yml, config/routes.rb
Adiconada chamada ajax para auxílio no preenchimento do campo UF.
=> Consetado o preenchimento automático no campo UF issue #359

app/controllers/events_controller.rb, app/views/events/index.html.erb
Mostrando os eventos atuais primeiro, e aviso de qual a situação do evento, encerrado, inscrições abertas e inscrições em breve.
=> Ordenado eventos e com aviso issue #356

app/views/events/_form.html.erb, app/views/events/edit.html.erb, app/views/events/new.html.erb
Adicionado painéis para separação dos formulários aninhados.
=> Tela de cadastro de eventos ajustada issue #358

app/views/home/index.html.erb
As notícias foram separadas discretamente por painéis do bootstrap.
=> Separando as notícias issue #364

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/users_controller.rb, app/views/registrations/_registration.html.erb, config/routes.rb, lib/tasks/dev.rake
Foi adicionada a gem 'bootstrap-editable-rails' como desejado na issue.
=> Editar nome do usuário direto na tela de registrations issue #366

app/controllers/events_controller.rb, app/views/event_registrations/index.html.erb, config/routes.rb
Possível de criar usuário na tela de registration, registrando ele no evento e marcando presença.
=> Cadastrando usuários na tela de registration issue #367

app/controllers/api/v1/events_controller.rb, spec/requests/api/v1/events_spec.rb, spec/spec_helper.rb, spec/support/request_helpers.rb
=> Create request test for events api endpoint

app/models/event.rb, app/views/events/_form.html.erb
=> Add has_many users relationship to Event

README.md
=> Update discord invite Link

app/controllers/registrations_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb
=> Add terms of use validation
